# This is a basic workflow to help you get started with Actions

name: Python application test

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ origin/master ]
  pull_request:
    branches: [ origin/master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Sets up a Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Replace with the Python version you need

    # Installs dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: List tests directory
      run: ls tests


    # Run tests
    - name: Run tests
      run: |
        python -m unittest tests.login_page_tests
